//package lab1package;
//
//public class Qn11_TryCatchFinally {
//	public static void main(String[] args) {
//		try {
//			int[] arr = new int[4];
//			int i = arr[4]; // this statement will throw exception
//			System.out.println("Inside try block");
//		} catch (ArrayIndexOutOfBoundsException ex) {
//			System.out.println("Exception has been caught.");
//		} finally {
//			System.out.println("Inside the finally block.");
//		}
//	}
//}
